/// Flutter icons HarshIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HarshIcons
///      fonts:
///       - asset: fonts/HarshIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class HarshIcons {
  HarshIcons._();

  static const _kFontFam = 'HarshIcons';
  static const String? _kFontPkg = null;

  // ignore: constant_identifier_names
  static const IconData account_in_bottom_bar =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
